---
title: "Data Visualization"
toc: false
page-layout: full
---
### Schema

- A very brief history of visualizations  
- Visualization elements  
- What do we want to communicate?  

### Slides

::: {.slides-preview}

<iframe 
  src="https://docs.google.com/presentation/d/1xB244Mj8_gZHD-ZvkvBxXsBWnUzdVFqr6C8IrL3HuiM/embed?start=false&loop=false&delayms=3000" 
  frameborder="0" 
  width="960" 
  height="569" 
  allowfullscreen="true" 
  mozallowfullscreen="true" 
  webkitallowfullscreen="true">
</iframe>

:::

### Resources

- Cairo, A. (2020). *How Charts Lie: Getting Smarter About Visual Information* (Norton paperback edition). W. W. Norton & Company, Inc.  

- Drucker, J. (2014). *Graphesis: Visual Forms of Knowledge Production*. Harvard University Press.  

- Meirelles, I. (2013). *Design for Information: An Introduction to the Histories, Theories, and Best Practices Behind Effective Information Visualizations* (1st edition). Rockport Publishers.  





<div style="font-size:0.9em;color:#555;margin-top:40px;border-top:1px solid #eee;padding-top:15px;">
© 2025 Coding Provenance Workshop — Licensed under a 
<a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">Creative Commons Attribution 4.0 International License</a>.  
Reuse is encouraged — we happily promote changes of custody. Just be sure to write a good provenance record and **cite this workshop**.
</div>