---
title: "Learning How to Code"
toc: false
page-layout: full
---
### Schema
- What is Python? 
- Understanding Python as a language 
- Why generative AI is helpful for coding purposes 
- Writing good prompts 
- Get familiar with the environments – Google Colab 

### Tools & Links

- Python official website: <https://www.python.org/>
- Python documentation: <https://docs.python.org/3/>
- Google Colab: <https://colab.research.google.com/>


### Slides

::: {.slides-preview}

<iframe 
  src="https://docs.google.com/presentation/d/1Wl3yxneY-EuMd3VtQJj1MiZpPhXpEfXh8NF8ixP5yi8/embed?start=false&loop=false&delayms=3000" 
  frameborder="0" 
  width="960" 
  height="569" 
  allowfullscreen="true" 
  mozallowfullscreen="true" 
  webkitallowfullscreen="true">
</iframe>

:::

### Resources

- Karsdorp, F., Kestemont, M., & Riddell, A. (2021). *Humanities Data Analysis: Case Studies with Python*. Princeton University Press.  
  <https://www.humanitiesdataanalysis.org/>

- Karsdorp, F. *Python Programming for the Humanities*.  
  <https://www.karsdorp.io/python-course/>

- Walsh, Melanie (2021). *Intro to Cultural Analytics*.  
  <https://melaniewalsh.github.io/Intro-Cultural-Analytics/welcome.html>

- *Programming Historian*.  
  <https://programminghistorian.org/>

- Poirier, Lindsay (2020). “Ethnographies of Datasets: Teaching Critical Data Analysis through R Notebooks”.  
  <https://shorturl.at/lAUgn>

---

<div style="font-size:0.9em;color:#555;margin-top:40px;border-top:1px solid #eee;padding-top:15px;">
© 2025 Coding Provenance Workshop — Licensed under a 
<a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">Creative Commons Attribution 4.0 International License</a>.  
Reuse is encouraged — we happily promote changes of custody. Just be sure to write a good provenance record and **cite this workshop**.
</div>